export const ExampleData = [
  {
    id: "012da82b-84f6-48a3-bf18-349846a87690",
    namaKepalaKeluarga: "I WAYAN YUDIANA",
    alamat: "SAGA LC SUBAK AYA BEBALANG",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "f4bf7fcf-e0b3-4ee8-8fdf-6e1225b454a5",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "f4bf7fcf-e0b3-4ee8-8fdf-6e1225b454a5",
          nama: "I WAYAN YUDIANA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BEBALANG",
          tanggalLahir: "1983-02-15",
          agama: "HINDU",
          pendidikan: "SLTP / Sederajat",
          jenisPekerjaan: "Pedagang",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I WAYAN KEMBAR",
          namaIbu: "NI WAYAN SUENTEN",
          banjar: "Bebalang",
          kkRef: "012da82b-84f6-48a3-bf18-349846a87690",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "wayan", "yudiana"],
          namaLowerCase: "i wayan yudiana",
        },
      },
      {
        pendudukId: "f904be8d-2dab-4591-83fd-7f2ccaa5cc9c",
        statusHubunganDalamKeluarga: "Istri",
        detail: {
          id: "f904be8d-2dab-4591-83fd-7f2ccaa5cc9c",
          nama: "NI KETUT SIMPEN",
          jenisKelamin: "Perempuan",
          tempatLahir: "BEBALANG",
          tanggalLahir: "1983-04-16",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Pedagang",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I NENGAH PICA",
          namaIbu: "NI NYOMAN KAREN",
          banjar: "Bebalang",
          kkRef: "012da82b-84f6-48a3-bf18-349846a87690",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "ketut", "simpen"],
          namaLowerCase: "ni ketut simpen",
        },
      },
      {
        pendudukId: "d2471904-741f-4728-b5af-18cfa2b4d86e",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "d2471904-741f-4728-b5af-18cfa2b4d86e",
          nama: "NI LUH PUTU SUTRESNI",
          jenisKelamin: "Perempuan",
          tempatLahir: "BANGLI",
          tanggalLahir: "2004-02-16",
          agama: "HINDU",
          pendidikan: "Belum Tamat SD / Sederajat",
          jenisPekerjaan: "Pelajar / Mahasiswa",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I WAYAN YUDIANA",
          namaIbu: "NI KETUT SIMPEN",
          banjar: "Bebalang",
          kkRef: "012da82b-84f6-48a3-bf18-349846a87690",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "luh", "putu", "sutresni"],
          namaLowerCase: "ni luh putu sutresni",
        },
      },
      {
        pendudukId: "337b9bfe-782a-4830-aa64-d60457a2fb22",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "337b9bfe-782a-4830-aa64-d60457a2fb22",
          nama: "NI KADEK WIDIANI",
          jenisKelamin: "Perempuan",
          tempatLahir: "BANGLI",
          tanggalLahir: "2010-09-22",
          agama: "HINDU",
          pendidikan: "Belum Tamat SD / Sederajat",
          jenisPekerjaan: "Pelajar / Mahasiswa",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I WAYAN YUDIANA",
          namaIbu: "NI KETUT SIMPEN",
          banjar: "Bebalang",
          kkRef: "012da82b-84f6-48a3-bf18-349846a87690",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "kadek", "widiani"],
          namaLowerCase: "ni kadek widiani",
        },
      },
      {
        pendudukId: "85cd4552-829d-4ec2-b22f-e91c0c39bc90",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "85cd4552-829d-4ec2-b22f-e91c0c39bc90",
          nama: "NI KOMANG RATIH BUDIANI",
          jenisKelamin: "Perempuan",
          tempatLahir: "BANGLI",
          tanggalLahir: "2011-02-16",
          agama: "HINDU",
          pendidikan: "Tidak / Belum Sekolah",
          jenisPekerjaan: "Belum / Tidak Bekerja",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I WAYAN YUDIANA",
          namaIbu: "NI KETUT SIMPEN",
          banjar: "Bebalang",
          kkRef: "012da82b-84f6-48a3-bf18-349846a87690",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "komang", "ratih", "budiani"],
          namaLowerCase: "ni komang ratih budiani",
        },
      },
      {
        pendudukId: "4c857aba-0944-401d-93f1-226ddc034181",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "4c857aba-0944-401d-93f1-226ddc034181",
          nama: "I KETUT SUKADANA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BANGLI",
          tanggalLahir: "2015-11-10",
          agama: "HINDU",
          pendidikan: "Tidak / Belum Sekolah",
          jenisPekerjaan: "Belum / Tidak Bekerja",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I WAYAN YUDIANA",
          namaIbu: "NI KETUT SIMPEN",
          banjar: "Bebalang",
          kkRef: "012da82b-84f6-48a3-bf18-349846a87690",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "ketut", "sukadana"],
          namaLowerCase: "i ketut sukadana",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
  {
    id: "47ef4499-ee24-49f0-994b-03dd9d516642",
    namaKepalaKeluarga: "I KOMANG SULASTRA",
    alamat: "BR. SEDIT",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "7df61e23-81f4-4531-8642-703645f34e0d",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "7df61e23-81f4-4531-8642-703645f34e0d",
          nama: "I KOMANG SULASTRA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "SELULUNG",
          tanggalLahir: "1981-09-16",
          agama: "HINDU",
          pendidikan: "Diploma I / II",
          jenisPekerjaan: "Wiraswasta",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I MADE DARMI",
          namaIbu: "NI WAYAN SELAMAT",
          banjar: "Bebalang",
          kkRef: "47ef4499-ee24-49f0-994b-03dd9d516642",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "komang", "sulastra"],
          namaLowerCase: "i komang sulastra",
        },
      },
      {
        pendudukId: "a8f1e4c1-cdc2-4443-a799-6423d7e7e178",
        statusHubunganDalamKeluarga: "Istri",
        detail: {
          id: "a8f1e4c1-cdc2-4443-a799-6423d7e7e178",
          nama: "NI LUH PUTU DESY WULANDARI",
          jenisKelamin: "Perempuan",
          tempatLahir: "KINTAMANI",
          tanggalLahir: "1992-11-12",
          agama: "HINDU",
          pendidikan: "Diploma IV / Strata I",
          jenisPekerjaan: "Karyawan Swasta",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "O",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I MADE SIMANTARA",
          namaIbu: "NI NENGAH SURYANI",
          banjar: "Bebalang",
          kkRef: "47ef4499-ee24-49f0-994b-03dd9d516642",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "luh", "putu", "desy", "wulandari"],
          namaLowerCase: "ni luh putu desy wulandari",
        },
      },
      {
        pendudukId: "326578e6-549d-4ed2-b9ee-69163e5b5a5b",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "326578e6-549d-4ed2-b9ee-69163e5b5a5b",
          nama: "I GEDE DHIKA PRATAMA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BANGLI",
          tanggalLahir: "2003-02-12",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Pelajar / Mahasiswa",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I KOMANG SULASTRA,A.MD.KOM",
          namaIbu: "NI WAYAN AGUSTINI",
          banjar: "Bebalang",
          kkRef: "47ef4499-ee24-49f0-994b-03dd9d516642",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "gede", "dhika", "pratama"],
          namaLowerCase: "i gede dhika pratama",
        },
      },
      {
        pendudukId: "63735efc-2ef3-4f1d-b57d-2219e8c0c466",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "63735efc-2ef3-4f1d-b57d-2219e8c0c466",
          nama: "I KADEK GANENDRA SULASTRA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BANGLI",
          tanggalLahir: "2018-02-05",
          agama: "HINDU",
          pendidikan: "Tidak / Belum Sekolah",
          jenisPekerjaan: "Belum / Tidak Bekerja",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I KOMANG SULASTRA",
          namaIbu: "NI LUH PUTU DESY WULANDARI",
          banjar: "Bebalang",
          kkRef: "47ef4499-ee24-49f0-994b-03dd9d516642",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "kadek", "ganendra", "sulastra"],
          namaLowerCase: "i kadek ganendra sulastra",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
  {
    id: "5191aebb-9c98-409f-97b6-74f3ee06e02e",
    namaKepalaKeluarga: "I NYOMAN SURAJA",
    alamat: "LINGK/BEBALANG",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "d270a4a8-9d0c-4c15-a42b-d235b661eb05",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "d270a4a8-9d0c-4c15-a42b-d235b661eb05",
          nama: "I NYOMAN SURAJA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BEBALANG",
          tanggalLahir: "1972-03-01",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Pegawai Negeri Sipil (PNS)",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "A",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "NYOMAN WIRIYA",
          namaIbu: "-",
          banjar: "Bebalang",
          kkRef: "5191aebb-9c98-409f-97b6-74f3ee06e02e",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "nyoman", "suraja"],
          namaLowerCase: "i nyoman suraja",
        },
      },
      {
        pendudukId: "14f86594-5f28-46d0-843b-2b3ff6f63a8a",
        statusHubunganDalamKeluarga: "Istri",
        detail: {
          id: "14f86594-5f28-46d0-843b-2b3ff6f63a8a",
          nama: "DESAK KETUT ALIT",
          jenisKelamin: "Perempuan",
          tempatLahir: "KINTAMANI",
          tanggalLahir: "1972-12-31",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Karyawan Honorer",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "-",
          namaIbu: "-",
          banjar: "Bebalang",
          kkRef: "5191aebb-9c98-409f-97b6-74f3ee06e02e",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["desak", "ketut", "alit"],
          namaLowerCase: "desak ketut alit",
        },
      },
      {
        pendudukId: "0b782ca2-93c9-405e-8d95-59433b24bab4",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "0b782ca2-93c9-405e-8d95-59433b24bab4",
          nama: "I KOMANG JATU PATRIASENA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BANGLI",
          tanggalLahir: "2004-07-01",
          agama: "HINDU",
          pendidikan: "Belum Tamat SD / Sederajat",
          jenisPekerjaan: "Pelajar / Mahasiswa",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I NYOMAN SURAJA",
          namaIbu: "DESAK KETUT ALIT",
          banjar: "Bebalang",
          kkRef: "5191aebb-9c98-409f-97b6-74f3ee06e02e",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "komang", "jatu", "patriasena"],
          namaLowerCase: "i komang jatu patriasena",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
  {
    id: "f26c4a5f-6430-4037-9bba-2e5ef2cb1756",
    namaKepalaKeluarga: "I KADEK HENDRAWAN",
    alamat: "LINGK/BR. TEGAL, KEL. BEBALANG, BANGLI",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "c0279d29-d3e7-44e9-b872-b621a21c6b10",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "c0279d29-d3e7-44e9-b872-b621a21c6b10",
          nama: "I KADEK HENDRAWAN",
          jenisKelamin: "Laki-laki",
          tempatLahir: "LINGK/BR.TEGAL",
          tanggalLahir: "1970-03-09",
          agama: "HINDU",
          pendidikan: "Diploma IV / Strata I",
          jenisPekerjaan: "Pegawai Negeri Sipil (PNS)",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "O",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I MADE WETNING",
          namaIbu: "NI KETUT KUMPUL",
          banjar: "Bebalang",
          kkRef: "f26c4a5f-6430-4037-9bba-2e5ef2cb1756",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "kadek", "hendrawan"],
          namaLowerCase: "i kadek hendrawan",
        },
      },
      {
        pendudukId: "848d6aa7-9bd9-48ab-8f62-86ec9a873ae0",
        statusHubunganDalamKeluarga: "Istri",
        detail: {
          id: "848d6aa7-9bd9-48ab-8f62-86ec9a873ae0",
          nama: "NI WAYAN KARTINI",
          jenisKelamin: "Perempuan",
          tempatLahir: "LINGK/BR.TEGAL",
          tanggalLahir: "1971-04-20",
          agama: "HINDU",
          pendidikan: "SLTA / Sederajat",
          jenisPekerjaan: "Perdagangan",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I NYOMAN BANDA",
          namaIbu: "NI KETUT CELETET",
          banjar: "Bebalang",
          kkRef: "f26c4a5f-6430-4037-9bba-2e5ef2cb1756",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "wayan", "kartini"],
          namaLowerCase: "ni wayan kartini",
        },
      },
      {
        pendudukId: "0bd61b24-be52-4589-8f77-ff924174a711",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "0bd61b24-be52-4589-8f77-ff924174a711",
          nama: "BAGUS KOMANG THRESNA BAYU ANUGRAH",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BANGLI",
          tanggalLahir: "1998-01-02",
          agama: "HINDU",
          pendidikan: "Diploma IV / Strata I",
          jenisPekerjaan: "Belum / Tidak Bekerja",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "O",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I KADEK HENDRAWAN",
          namaIbu: "NI WAYAN KARTINI",
          banjar: "Bebalang",
          kkRef: "f26c4a5f-6430-4037-9bba-2e5ef2cb1756",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["bagus", "komang", "thresna", "bayu", "anugrah"],
          namaLowerCase: "bagus komang thresna bayu anugrah",
        },
      },
      {
        pendudukId: "daa713c4-9b95-4b4f-841b-a6feabd0796e",
        statusHubunganDalamKeluarga: "Orang Tua",
        detail: {
          id: "daa713c4-9b95-4b4f-841b-a6feabd0796e",
          nama: "I MADE WETNING",
          jenisKelamin: "Perempuan",
          tempatLahir: "LINGK/BR.TEGAL",
          tanggalLahir: "1935-01-07",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Petani / Pekebun",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "O",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I TRAGIA",
          namaIbu: "NI MANIS",
          banjar: "Bebalang",
          kkRef: "f26c4a5f-6430-4037-9bba-2e5ef2cb1756",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "made", "wetning"],
          namaLowerCase: "i made wetning",
        },
      },
      {
        pendudukId: "454f8d54-fd77-451a-9f89-af930f9a18ec",
        statusHubunganDalamKeluarga: "Orang Tua",
        detail: {
          id: "454f8d54-fd77-451a-9f89-af930f9a18ec",
          nama: "NI KETUT KUMPUL",
          jenisKelamin: "Perempuan",
          tempatLahir: "BANGLI",
          tanggalLahir: "1938-01-07",
          agama: "HINDU",
          pendidikan: "Tidak / Belum Sekolah",
          jenisPekerjaan: "Petani / Pekebun",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "O",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I KEPIR",
          namaIbu: "NI RORAS",
          banjar: "Bebalang",
          kkRef: "f26c4a5f-6430-4037-9bba-2e5ef2cb1756",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "ketut", "kumpul"],
          namaLowerCase: "ni ketut kumpul",
        },
      },
      {
        pendudukId: "234e4cfc-e851-4c20-9d8d-508be65e3295",
        statusHubunganDalamKeluarga: "Famili Lain",
        detail: {
          id: "234e4cfc-e851-4c20-9d8d-508be65e3295",
          nama: "NI NYOMAN MUDIASTRI",
          jenisKelamin: "Perempuan",
          tempatLahir: "LINGK/BR.TEGAL",
          tanggalLahir: "1963-01-07",
          agama: "HINDU",
          pendidikan: "SLTA / Sederajat",
          jenisPekerjaan: "Perdagangan",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "O",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I MADE WETNING",
          namaIbu: "NI KETUT KUMPUL",
          banjar: "Bebalang",
          kkRef: "f26c4a5f-6430-4037-9bba-2e5ef2cb1756",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "nyoman", "mudiastri"],
          namaLowerCase: "ni nyoman mudiastri",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
  {
    id: "132feaa6-0488-4491-870a-efa4856e685d",
    namaKepalaKeluarga: "SUPRIYANTO",
    alamat: "LINGK/BR.PETAK",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "19191271-17c5-442a-a44d-20decb69da8f",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "19191271-17c5-442a-a44d-20decb69da8f",
          nama: "SUPRIYANTO",
          jenisKelamin: "Laki-laki",
          tempatLahir: "PONOROGO",
          tanggalLahir: "1971-07-27",
          agama: "ISLAM",
          pendidikan: "SLTP / Sederajat",
          jenisPekerjaan: "Karyawan Swasta",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "SUPRAPTO",
          namaIbu: "T.SARIPAH",
          banjar: "Bebalang",
          kkRef: "132feaa6-0488-4491-870a-efa4856e685d",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["supriyanto"],
          namaLowerCase: "supriyanto",
        },
      },
      {
        pendudukId: "665fa7b2-db5c-49b6-bb36-3f778520dd00",
        statusHubunganDalamKeluarga: "Istri",
        detail: {
          id: "665fa7b2-db5c-49b6-bb36-3f778520dd00",
          nama: "NYOMAN PURNAWATI",
          jenisKelamin: "Perempuan",
          tempatLahir: "BANGLI",
          tanggalLahir: "1981-12-31",
          agama: "ISLAM",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Mengurus Rumah Tangga",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "NYOMAN WIDIA NEGARA",
          namaIbu: "NI NENGAH SUSUN ",
          banjar: "Bebalang",
          kkRef: "132feaa6-0488-4491-870a-efa4856e685d",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["nyoman", "purnawati"],
          namaLowerCase: "nyoman purnawati",
        },
      },
      {
        pendudukId: "ce6d42b1-b601-4afa-9324-15f7d9193092",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "ce6d42b1-b601-4afa-9324-15f7d9193092",
          nama: "AGUNG HADI NUGROHO",
          jenisKelamin: "Laki-laki",
          tempatLahir: "GIANYAR",
          tanggalLahir: "2008-05-14",
          agama: "ISLAM",
          pendidikan: "Belum Tamat SD / Sederajat",
          jenisPekerjaan: "Pelajar / Mahasiswa",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "SUPRIYANTO",
          namaIbu: "NYOMAN PURNAWATI",
          banjar: "Bebalang",
          kkRef: "132feaa6-0488-4491-870a-efa4856e685d",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["agung", "hadi", "nugroho"],
          namaLowerCase: "agung hadi nugroho",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
  {
    id: "5aad2ce0-b3f0-4fb0-afa4-0d866208183f",
    namaKepalaKeluarga: "I NYOMAN SUMIRDA",
    alamat: "LINGK/BR TEGAL",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "bf2327ac-6da1-4e55-9fa7-97bcb61ba33d",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "bf2327ac-6da1-4e55-9fa7-97bcb61ba33d",
          nama: "I NYOMAN SUMIRDA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "LINGK/BR. TEGAL",
          tanggalLahir: "1968-12-31",
          agama: "HINDU",
          pendidikan: "SLTA / Sederajat",
          jenisPekerjaan: "Petani / Pekebun",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I KETUT KANTOR",
          namaIbu: "NI NYOMAN BELIH",
          banjar: "Bebalang",
          kkRef: "5aad2ce0-b3f0-4fb0-afa4-0d866208183f",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "nyoman", "sumirda"],
          namaLowerCase: "i nyoman sumirda",
        },
      },
      {
        pendudukId: "1abbf8e5-2d29-4e0b-a0d1-388882ffb6b9",
        statusHubunganDalamKeluarga: "Istri",
        detail: {
          id: "1abbf8e5-2d29-4e0b-a0d1-388882ffb6b9",
          nama: "NI WAYAN SARIANI",
          jenisKelamin: "Perempuan",
          tempatLahir: "LINGK/BR. TEGAL",
          tanggalLahir: "1965-12-31",
          agama: "HINDU",
          pendidikan: "SLTA / Sederajat",
          jenisPekerjaan: "Petani / Pekebun",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I WAYAN JENIR",
          namaIbu: "NI NYOMAN BUKTI",
          banjar: "Bebalang",
          kkRef: "5aad2ce0-b3f0-4fb0-afa4-0d866208183f",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "wayan", "sariani"],
          namaLowerCase: "ni wayan sariani",
        },
      },
      {
        pendudukId: "d2252656-c512-4ce2-903e-183e35a8237e",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "d2252656-c512-4ce2-903e-183e35a8237e",
          nama: "NI MADE WIDIARDANI",
          jenisKelamin: "Perempuan",
          tempatLahir: "BANGLI",
          tanggalLahir: "2001-09-22",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Pelajar / Mahasiswa",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I NYOMAN SUMIRDA",
          namaIbu: "NI WAYAN SARIANI",
          banjar: "Bebalang",
          kkRef: "5aad2ce0-b3f0-4fb0-afa4-0d866208183f",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "made", "widiardani"],
          namaLowerCase: "ni made widiardani",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
  {
    id: "b5fd22d3-2290-4ecf-abf2-5afab1645e66",
    namaKepalaKeluarga: "I KETUT KANTOR",
    alamat: "LINGK- BR PETAK",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "244ac9a2-17e0-4c92-ab25-4cdea51359dc",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "244ac9a2-17e0-4c92-ab25-4cdea51359dc",
          nama: "I KETUT KANTOR",
          jenisKelamin: "Laki-laki",
          tempatLahir: "PETAK",
          tanggalLahir: "1968-12-31",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Tukang Kayu",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I WAYAN RAUH",
          namaIbu: "NI NENGAH MUNUH",
          banjar: "Bebalang",
          kkRef: "b5fd22d3-2290-4ecf-abf2-5afab1645e66",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "ketut", "kantor"],
          namaLowerCase: "i ketut kantor",
        },
      },
      {
        pendudukId: "4ff46ab8-7078-4adf-90cf-4723d343c17d",
        statusHubunganDalamKeluarga: "Istri",
        detail: {
          id: "4ff46ab8-7078-4adf-90cf-4723d343c17d",
          nama: "NI WAYAN SUMIATI",
          jenisKelamin: "Perempuan",
          tempatLahir: "JAWA TIMUR",
          tanggalLahir: "1968-12-29",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Perdagangan",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "SOELEMAN",
          namaIbu: "MEN SUMIATI",
          banjar: "Bebalang",
          kkRef: "b5fd22d3-2290-4ecf-abf2-5afab1645e66",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "wayan", "sumiati"],
          namaLowerCase: "ni wayan sumiati",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
  {
    id: "2c78303d-6574-45cb-ac81-43f1f632d057",
    namaKepalaKeluarga: "I NENGAH KOBET",
    alamat: "LINGK./BR. TEGAL",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "6c13be4c-45bb-4170-b47a-61e9acff732e",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "6c13be4c-45bb-4170-b47a-61e9acff732e",
          nama: "I NENGAH KOBET",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BR. TEGAL",
          tanggalLahir: "1955-12-31",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Petani / Pekebun",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "ALM",
          namaIbu: "ALM",
          banjar: "Bebalang",
          kkRef: "2c78303d-6574-45cb-ac81-43f1f632d057",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "nengah", "kobet"],
          namaLowerCase: "i nengah kobet",
        },
      },
      {
        pendudukId: "cb764467-9fb6-4314-8ad2-3aee1df3afac",
        statusHubunganDalamKeluarga: "Famili Lain",
        detail: {
          id: "cb764467-9fb6-4314-8ad2-3aee1df3afac",
          nama: "NI WAYAN GABUR",
          jenisKelamin: "Perempuan",
          tempatLahir: "BR. TEGAL",
          tanggalLahir: "1957-12-31",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Petani / Pekebun",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "ALM",
          namaIbu: "ALM",
          banjar: "Bebalang",
          kkRef: "2c78303d-6574-45cb-ac81-43f1f632d057",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "wayan", "gabur"],
          namaLowerCase: "ni wayan gabur",
        },
      },
      {
        pendudukId: "5529a209-f3d1-430c-8917-6bfa2f3a0630",
        statusHubunganDalamKeluarga: "Famili Lain",
        detail: {
          id: "5529a209-f3d1-430c-8917-6bfa2f3a0630",
          nama: "I KETUT TUNTUT",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BR. TEGAL",
          tanggalLahir: "1960-12-31",
          agama: "HINDU",
          pendidikan: "SLTA / Sederajat",
          jenisPekerjaan: "Pegawai Negeri Sipil (PNS)",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "ALM",
          namaIbu: "ALM",
          banjar: "Bebalang",
          kkRef: "2c78303d-6574-45cb-ac81-43f1f632d057",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "ketut", "tuntut"],
          namaLowerCase: "i ketut tuntut",
        },
      },
      {
        pendudukId: "38a563d7-68a2-4b21-86a8-2f5115a4d999",
        statusHubunganDalamKeluarga: "Famili Lain",
        detail: {
          id: "38a563d7-68a2-4b21-86a8-2f5115a4d999",
          nama: "I WAYAN SEPIH",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BR. TEGAL",
          tanggalLahir: "1962-12-31",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Pegawai Negeri Sipil (PNS)",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "ALM",
          namaIbu: "ALM",
          banjar: "Bebalang",
          kkRef: "2c78303d-6574-45cb-ac81-43f1f632d057",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "wayan", "sepih"],
          namaLowerCase: "i wayan sepih",
        },
      },
      {
        pendudukId: "03f3f9c9-6b44-4ef3-bcc1-428577c1cbae",
        statusHubunganDalamKeluarga: "Famili Lain",
        detail: {
          id: "03f3f9c9-6b44-4ef3-bcc1-428577c1cbae",
          nama: "I NENGAH TENU",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BR. TEGAL",
          tanggalLahir: "1967-12-31",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Petani / Pekebun",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "ALM",
          namaIbu: "ALM",
          banjar: "Bebalang",
          kkRef: "2c78303d-6574-45cb-ac81-43f1f632d057",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "nengah", "tenu"],
          namaLowerCase: "i nengah tenu",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
  {
    id: "32f319cf-7dac-4a57-bc56-54e79c11f34a",
    namaKepalaKeluarga: "I GUSTI PUTU TIRTAYASA",
    alamat: "TEMPEK PULUNG KAUH, LINGK/BR. BEBALANG",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "bb05a7a2-970d-456e-a7bf-2b46749d56ac",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "bb05a7a2-970d-456e-a7bf-2b46749d56ac",
          nama: "I GUSTI PUTU TIRTAYASA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "PETAK",
          tanggalLahir: "1988-02-20",
          agama: "HINDU",
          pendidikan: "SLTA / Sederajat",
          jenisPekerjaan: "Karyawan Swasta",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I GUSTI KETUT MUSTIKA",
          namaIbu: "GUSTI AYU SIRAT ALM",
          banjar: "Bebalang",
          kkRef: "32f319cf-7dac-4a57-bc56-54e79c11f34a",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "gusti", "putu", "tirtayasa"],
          namaLowerCase: "i gusti putu tirtayasa",
        },
      },
      {
        pendudukId: "5f626ef3-84d5-434b-a011-04361a7bd307",
        statusHubunganDalamKeluarga: "Istri",
        detail: {
          id: "5f626ef3-84d5-434b-a011-04361a7bd307",
          nama: "NI KADEK SUARTINI",
          jenisKelamin: "Perempuan",
          tempatLahir: "TELUNWAYAH",
          tanggalLahir: "1996-07-28",
          agama: "HINDU",
          pendidikan: "SLTA / Sederajat",
          jenisPekerjaan: "Wiraswasta",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I KETUT MURTIKA",
          namaIbu: "NI NENGAH SUDIARNI",
          banjar: "Bebalang",
          kkRef: "32f319cf-7dac-4a57-bc56-54e79c11f34a",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "kadek", "suartini"],
          namaLowerCase: "ni kadek suartini",
        },
      },
      {
        pendudukId: "b41c6db9-45bb-417d-a4ac-96e7664072fe",
        statusHubunganDalamKeluarga: "Anak",
        detail: {
          id: "b41c6db9-45bb-417d-a4ac-96e7664072fe",
          nama: "I GUSTI AYU PUTRI WIDYA ARSITA",
          jenisKelamin: "Perempuan",
          tempatLahir: "BANGLI",
          tanggalLahir: "2016-08-24",
          agama: "HINDU",
          pendidikan: "Tidak / Belum Sekolah",
          jenisPekerjaan: "Belum / Tidak Bekerja",
          statusPerkawinan: "",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I GUSTI PUTU TIRTAYASA",
          namaIbu: "NI KADEK SUARTINI",
          banjar: "Bebalang",
          kkRef: "32f319cf-7dac-4a57-bc56-54e79c11f34a",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "gusti", "ayu", "putri", "widya", "arsita"],
          namaLowerCase: "i gusti ayu putri widya arsita",
        },
      },
      {
        pendudukId: "e27d57dc-70a9-415f-a005-af7a1c0dd0ab",
        statusHubunganDalamKeluarga: "Orang Tua",
        detail: {
          id: "e27d57dc-70a9-415f-a005-af7a1c0dd0ab",
          nama: "I GUSTI KETUT MUSTIKA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "BEBALANG",
          tanggalLahir: "1960-12-31",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Petani / Pekebun",
          statusPerkawinan: "Cerai Mati",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "GUSTI PUTU KANDA (ALM)",
          namaIbu: "GUSTI AYU MARA (ALM)",
          banjar: "Bebalang",
          kkRef: "32f319cf-7dac-4a57-bc56-54e79c11f34a",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "gusti", "ketut", "mustika"],
          namaLowerCase: "i gusti ketut mustika",
        },
      },
      {
        pendudukId: "17897567-32ed-4139-ac8e-7b51fe6b1fd3",
        statusHubunganDalamKeluarga: "Orang Tua",
        detail: {
          id: "17897567-32ed-4139-ac8e-7b51fe6b1fd3",
          nama: "NI NYOMAN SUMARNI",
          jenisKelamin: "Perempuan",
          tempatLahir: "BEBALANG",
          tanggalLahir: "1965-12-31",
          agama: "HINDU",
          pendidikan: "Tamat SD / Sederajat",
          jenisPekerjaan: "Perdagangan",
          statusPerkawinan: "Cerai Mati",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I WAYAN SANGKA (ALM)",
          namaIbu: "NI NYOMAN SUSUN (ALM)",
          banjar: "Bebalang",
          kkRef: "32f319cf-7dac-4a57-bc56-54e79c11f34a",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "nyoman", "sumarni"],
          namaLowerCase: "ni nyoman sumarni",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
  {
    id: "7df76bf5-14fe-416d-bf42-4d73e7d66b92",
    namaKepalaKeluarga: "I NYOMAN SUTARJA",
    alamat: "JLN.TUKAD PULU NO.5 LINGK/BR.BEBALANG",
    tanggalPenerbitan: "2025-08-07",
    banjar: "Bebalang",
    anggota: [
      {
        pendudukId: "0eabd179-ef26-48f8-8b8c-9b46903d05c0",
        statusHubunganDalamKeluarga: "Kepala Keluarga",
        detail: {
          id: "0eabd179-ef26-48f8-8b8c-9b46903d05c0",
          nama: "I NYOMAN SUTARJA",
          jenisKelamin: "Laki-laki",
          tempatLahir: "KLUNGKUNG",
          tanggalLahir: "1963-12-31",
          agama: "HINDU",
          pendidikan: "Diploma IV / Strata I",
          jenisPekerjaan: "Belum / Tidak Bekerja",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "A",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "I KETUT KEUG (ALM)",
          namaIbu: "NI NENGAH KOSOR (ALM)",
          banjar: "Bebalang",
          kkRef: "7df76bf5-14fe-416d-bf42-4d73e7d66b92",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["i", "nyoman", "sutarja"],
          namaLowerCase: "i nyoman sutarja",
        },
      },
      {
        pendudukId: "001cef2b-2472-4ac5-a9e0-e4e223a62387",
        statusHubunganDalamKeluarga: "Istri",
        detail: {
          id: "001cef2b-2472-4ac5-a9e0-e4e223a62387",
          nama: "NI KETUT SUCIATI",
          jenisKelamin: "Perempuan",
          tempatLahir: "KLUNGKUNG",
          tanggalLahir: "1963-02-16",
          agama: "HINDU",
          pendidikan: "Diploma IV / Strata I",
          jenisPekerjaan: "Karyawan BUMD",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "IDA PANDHITA MPU DAKSA ADNYANA",
          namaIbu: "IDA PANDITHA MPU PRAMI SARI",
          banjar: "Bebalang",
          kkRef: "7df76bf5-14fe-416d-bf42-4d73e7d66b92",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ni", "ketut", "suciati"],
          namaLowerCase: "ni ketut suciati",
        },
      },
      {
        pendudukId: "f0b78826-e954-40ee-8315-83c98f6ed6de",
        statusHubunganDalamKeluarga: "Mertua",
        detail: {
          id: "f0b78826-e954-40ee-8315-83c98f6ed6de",
          nama: "IDA PANDITHA MPU PRAMI SARI",
          jenisKelamin: "Perempuan",
          tempatLahir: "KLUNGKUNG",
          tanggalLahir: "1963-12-31",
          agama: "HINDU",
          pendidikan: "Belum Tamat SD / Sederajat",
          jenisPekerjaan: "Wiraswasta",
          statusPerkawinan: "Kawin",
          kewarganegaraan: "WNI",
          golonganDarah: "",
          penyandangCacat: "Tidak Cacat",
          namaAyah: "ALM",
          namaIbu: "NI NENGAH CADEL (ALM)",
          banjar: "Bebalang",
          kkRef: "7df76bf5-14fe-416d-bf42-4d73e7d66b92",
          createdBy: ["sispendubebalang@gmail.com"],
          editedBy: ["sispendubebalang@gmail.com"],
          namaKeywords: ["ida", "panditha", "mpu", "prami", "sari"],
          namaLowerCase: "ida panditha mpu prami sari",
        },
      },
    ],
    createdBy: "sispendubebalang@gmail.com",
    editedBy: "sispendubebalang@gmail.com",
  },
];
